import pygame

FIRST_MENU = 0
LOGIN_MENU = 1
REGISTER_MENU = 2
HOME_MENU = 3
GAME_MODE_MENU = 4
CHOOSE_BOARD_MENU = 5
RULES_MENU = 6

# customs events for changing menus
CHANGE_TO_FIRST = pygame.USEREVENT + 1
CHANGE_TO_LOGIN = pygame.USEREVENT + 2
CHANGE_TO_REGISTER = pygame.USEREVENT + 3
CHANGE_TO_HOME = pygame.USEREVENT + 4
CHANGE_TO_GAMEMODE = pygame.USEREVENT + 5
CHANGE_TO_CHOOSE_BOARD = pygame.USEREVENT + 6
CHANGE_TO_RULES = pygame.USEREVENT + 7
